# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: fmt
      - task: build

  build:
    cmds:
      - go build -o ./bin/easyvirt ./cmd/easyvirt

  fmt:
    cmds:
      - go fmt ./...
      - bun x prettier -w .

  pb:
    cmds:
      - >
        protoc --go_out=. --go_opt=paths=source_relative
        --go-grpc_out=. --go-grpc_opt=paths=source_relative
        proto/easyvirt.proto

  install-deps:
    cmds:
      - sudo dnf install -y libvirt libvirt-devel
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install entgo.io/ent/cmd/ent@latest
