# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: fmt

  fmt:
    cmds:
      - go fmt ./...
      - bun x prettier -w .

  pb:
    cmds:
      - >
        protoc --go_out=proto/ --go_opt=paths=source_relative
        --go-grpc_out=proto/ --go-grpc_opt=paths=source_relative
        easyvirt.proto
