# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: fmt
      - task: build

  build:
    env:
      CGO_ENABLED: 1
    cmds:
      - go build -o ./bin/easyvirt ./cmd/easyvirt

  test:
    cmds:
      - go test ./...

  fmt:
    cmds:
      - go fmt ./...
      - bun x prettier -w .

  gen:
    cmds:
      - go generate ./ent
      - task: pb

  pb:
    cmds:
      - >
        protoc -Iproto --go_out=v1/disk --go_opt=paths=source_relative
        --go-grpc_out=v1/disk --go-grpc_opt=paths=source_relative
        proto/disk_manager.proto
      - >
        protoc -Iproto --go_out=v1/domain --go_opt=paths=source_relative
        --go-grpc_out=v1/domain --go-grpc_opt=paths=source_relative
        proto/easyvirt.proto

  install-deps:
    cmds:
      - sudo dnf install -y libvirt libvirt-devel
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install entgo.io/ent/cmd/ent@latest
