// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: easyvirt.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiskDeviceType int32

const (
	DiskDeviceType_DISK_DEVICE_TYPE_DISK  DiskDeviceType = 0
	DiskDeviceType_DISK_DEVICE_TYPE_CDROM DiskDeviceType = 1
)

// Enum value maps for DiskDeviceType.
var (
	DiskDeviceType_name = map[int32]string{
		0: "DISK_DEVICE_TYPE_DISK",
		1: "DISK_DEVICE_TYPE_CDROM",
	}
	DiskDeviceType_value = map[string]int32{
		"DISK_DEVICE_TYPE_DISK":  0,
		"DISK_DEVICE_TYPE_CDROM": 1,
	}
)

func (x DiskDeviceType) Enum() *DiskDeviceType {
	p := new(DiskDeviceType)
	*p = x
	return p
}

func (x DiskDeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskDeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_easyvirt_proto_enumTypes[0].Descriptor()
}

func (DiskDeviceType) Type() protoreflect.EnumType {
	return &file_easyvirt_proto_enumTypes[0]
}

func (x DiskDeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskDeviceType.Descriptor instead.
func (DiskDeviceType) EnumDescriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{0}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_easyvirt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{0}
}

type DomainID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainID) Reset() {
	*x = DomainID{}
	mi := &file_easyvirt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainID) ProtoMessage() {}

func (x *DomainID) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainID.ProtoReflect.Descriptor instead.
func (*DomainID) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{1}
}

func (x *DomainID) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DomainID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DiskDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceType    DiskDeviceType         `protobuf:"varint,1,opt,name=device_type,json=deviceType,proto3,enum=DiskDeviceType" json:"device_type,omitempty"`
	DriverType    string                 `protobuf:"bytes,2,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"` // raw, qcow2
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Bus           string                 `protobuf:"bytes,5,opt,name=bus,proto3" json:"bus,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,6,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskDescriptor) Reset() {
	*x = DiskDescriptor{}
	mi := &file_easyvirt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskDescriptor) ProtoMessage() {}

func (x *DiskDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskDescriptor.ProtoReflect.Descriptor instead.
func (*DiskDescriptor) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{2}
}

func (x *DiskDescriptor) GetDeviceType() DiskDeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DiskDeviceType_DISK_DEVICE_TYPE_DISK
}

func (x *DiskDescriptor) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *DiskDescriptor) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DiskDescriptor) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DiskDescriptor) GetBus() string {
	if x != nil {
		return x.Bus
	}
	return ""
}

func (x *DiskDescriptor) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type NicDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicDescriptor) Reset() {
	*x = NicDescriptor{}
	mi := &file_easyvirt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicDescriptor) ProtoMessage() {}

func (x *NicDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicDescriptor.ProtoReflect.Descriptor instead.
func (*NicDescriptor) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{3}
}

type VncDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VncDescriptor) Reset() {
	*x = VncDescriptor{}
	mi := &file_easyvirt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VncDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VncDescriptor) ProtoMessage() {}

func (x *VncDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VncDescriptor.ProtoReflect.Descriptor instead.
func (*VncDescriptor) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{4}
}

type VideoCardDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCardDescriptor) Reset() {
	*x = VideoCardDescriptor{}
	mi := &file_easyvirt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCardDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCardDescriptor) ProtoMessage() {}

func (x *VideoCardDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCardDescriptor.ProtoReflect.Descriptor instead.
func (*VideoCardDescriptor) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{5}
}

type VM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      *DomainID              `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	VcpuCount     uint64                 `protobuf:"varint,2,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	Memory        uint64                 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	BootDevices   []string               `protobuf:"bytes,9,rep,name=boot_devices,json=bootDevices,proto3" json:"boot_devices,omitempty"`
	DiskList      []*DiskDescriptor      `protobuf:"bytes,10,rep,name=disk_list,json=diskList,proto3" json:"disk_list,omitempty"`
	NicList       []*NicDescriptor       `protobuf:"bytes,11,rep,name=nic_list,json=nicList,proto3" json:"nic_list,omitempty"`
	VncList       []*VncDescriptor       `protobuf:"bytes,14,rep,name=vnc_list,json=vncList,proto3" json:"vnc_list,omitempty"`
	VideoCardList []*VideoCardDescriptor `protobuf:"bytes,15,rep,name=video_card_list,json=videoCardList,proto3" json:"video_card_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VM) Reset() {
	*x = VM{}
	mi := &file_easyvirt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{6}
}

func (x *VM) GetDomainId() *DomainID {
	if x != nil {
		return x.DomainId
	}
	return nil
}

func (x *VM) GetVcpuCount() uint64 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *VM) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *VM) GetBootDevices() []string {
	if x != nil {
		return x.BootDevices
	}
	return nil
}

func (x *VM) GetDiskList() []*DiskDescriptor {
	if x != nil {
		return x.DiskList
	}
	return nil
}

func (x *VM) GetNicList() []*NicDescriptor {
	if x != nil {
		return x.NicList
	}
	return nil
}

func (x *VM) GetVncList() []*VncDescriptor {
	if x != nil {
		return x.VncList
	}
	return nil
}

func (x *VM) GetVideoCardList() []*VideoCardDescriptor {
	if x != nil {
		return x.VideoCardList
	}
	return nil
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VM                    `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVMRequest) GetVm() *VM {
	if x != nil {
		return x.Vm
	}
	return nil
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{8}
}

func (x *GetVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type GetVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VM                    `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMResponse) Reset() {
	*x = GetVMResponse{}
	mi := &file_easyvirt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMResponse) ProtoMessage() {}

func (x *GetVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMResponse.ProtoReflect.Descriptor instead.
func (*GetVMResponse) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{9}
}

func (x *GetVMResponse) GetVm() *VM {
	if x != nil {
		return x.Vm
	}
	return nil
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Inactive      bool                   `protobuf:"varint,2,opt,name=inactive,proto3" json:"inactive,omitempty"`
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_easyvirt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{10}
}

func (x *ListVMsRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ListVMsRequest) GetInactive() bool {
	if x != nil {
		return x.Inactive
	}
	return false
}

func (x *ListVMsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VM                  `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_easyvirt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{11}
}

func (x *ListVMsResponse) GetVms() []*VM {
	if x != nil {
		return x.Vms
	}
	return nil
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{12}
}

func (x *StartVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type StopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // destory domain or not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{13}
}

func (x *StopVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *StopVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RestartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartVMRequest) Reset() {
	*x = RestartVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVMRequest) ProtoMessage() {}

func (x *RestartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartVMRequest.ProtoReflect.Descriptor instead.
func (*RestartVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{14}
}

func (x *RestartVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RestartVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PauseVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVMRequest) Reset() {
	*x = PauseVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVMRequest) ProtoMessage() {}

func (x *PauseVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVMRequest.ProtoReflect.Descriptor instead.
func (*PauseVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{15}
}

func (x *PauseVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ResumeVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVMRequest) Reset() {
	*x = ResumeVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVMRequest) ProtoMessage() {}

func (x *ResumeVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVMRequest.ProtoReflect.Descriptor instead.
func (*ResumeVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{16}
}

func (x *ResumeVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DeleteDisks   bool                   `protobuf:"varint,2,opt,name=delete_disks,json=deleteDisks,proto3" json:"delete_disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *DeleteVMRequest) GetDeleteDisks() bool {
	if x != nil {
		return x.DeleteDisks
	}
	return false
}

type UpdateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVMRequest) Reset() {
	*x = UpdateVMRequest{}
	mi := &file_easyvirt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVMRequest) ProtoMessage() {}

func (x *UpdateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_easyvirt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVMRequest.ProtoReflect.Descriptor instead.
func (*UpdateVMRequest) Descriptor() ([]byte, []int) {
	return file_easyvirt_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

var File_easyvirt_proto protoreflect.FileDescriptor

const file_easyvirt_proto_rawDesc = "" +
	"\n" +
	"\x0eeasyvirt.proto\"\x06\n" +
	"\x04Void\"B\n" +
	"\bDomainID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"\xd0\x01\n" +
	"\x0eDiskDescriptor\x120\n" +
	"\vdevice_type\x18\x01 \x01(\x0e2\x0f.DiskDeviceTypeR\n" +
	"deviceType\x12\x1f\n" +
	"\vdriver_type\x18\x02 \x01(\tR\n" +
	"driverType\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x10\n" +
	"\x03bus\x18\x05 \x01(\tR\x03bus\x12\x1b\n" +
	"\tread_only\x18\x06 \x01(\bR\breadOnly\"\x0f\n" +
	"\rNicDescriptor\"\x0f\n" +
	"\rVncDescriptor\"\x15\n" +
	"\x13VideoCardDescriptor\"\xc8\x02\n" +
	"\x02VM\x12&\n" +
	"\tdomain_id\x18\x01 \x01(\v2\t.DomainIDR\bdomainId\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x02 \x01(\x04R\tvcpuCount\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x04R\x06memory\x12!\n" +
	"\fboot_devices\x18\t \x03(\tR\vbootDevices\x12,\n" +
	"\tdisk_list\x18\n" +
	" \x03(\v2\x0f.DiskDescriptorR\bdiskList\x12)\n" +
	"\bnic_list\x18\v \x03(\v2\x0e.NicDescriptorR\anicList\x12)\n" +
	"\bvnc_list\x18\x0e \x03(\v2\x0e.VncDescriptorR\avncList\x12<\n" +
	"\x0fvideo_card_list\x18\x0f \x03(\v2\x14.VideoCardDescriptorR\rvideoCardList\"&\n" +
	"\x0fCreateVMRequest\x12\x13\n" +
	"\x02vm\x18\x01 \x01(\v2\x03.VMR\x02vm\"1\n" +
	"\fGetVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"$\n" +
	"\rGetVMResponse\x12\x13\n" +
	"\x02vm\x18\x01 \x01(\v2\x03.VMR\x02vm\"V\n" +
	"\x0eListVMsRequest\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1a\n" +
	"\binactive\x18\x02 \x01(\bR\binactive\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"(\n" +
	"\x0fListVMsResponse\x12\x15\n" +
	"\x03vms\x18\x01 \x03(\v2\x03.VMR\x03vms\"3\n" +
	"\x0eStartVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"H\n" +
	"\rStopVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"K\n" +
	"\x10RestartVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"3\n" +
	"\x0ePauseVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"4\n" +
	"\x0fResumeVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"W\n" +
	"\x0fDeleteVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\x12!\n" +
	"\fdelete_disks\x18\x02 \x01(\bR\vdeleteDisks\"4\n" +
	"\x0fUpdateVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain*G\n" +
	"\x0eDiskDeviceType\x12\x19\n" +
	"\x15DISK_DEVICE_TYPE_DISK\x10\x00\x12\x1a\n" +
	"\x16DISK_DEVICE_TYPE_CDROM\x10\x012\x98\x03\n" +
	"\bEasyVirt\x12%\n" +
	"\bCreateVM\x12\x10.CreateVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bDeleteVM\x12\x10.DeleteVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bUpdateVM\x12\x10.UpdateVMRequest\x1a\x05.Void\"\x00\x12(\n" +
	"\x05GetVM\x12\r.GetVMRequest\x1a\x0e.GetVMResponse\"\x00\x12.\n" +
	"\aListVMs\x12\x0f.ListVMsRequest\x1a\x10.ListVMsResponse\"\x00\x12#\n" +
	"\aStartVM\x12\x0f.StartVMRequest\x1a\x05.Void\"\x00\x12!\n" +
	"\x06StopVM\x12\x0e.StopVMRequest\x1a\x05.Void\"\x00\x12'\n" +
	"\tRestartVM\x12\x11.RestartVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\tSuspendVM\x12\x0f.PauseVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bResumeVM\x12\x10.ResumeVMRequest\x1a\x05.Void\"\x00B)Z'github.com/fanyang89/easyvirt/v1/domainb\x06proto3"

var (
	file_easyvirt_proto_rawDescOnce sync.Once
	file_easyvirt_proto_rawDescData []byte
)

func file_easyvirt_proto_rawDescGZIP() []byte {
	file_easyvirt_proto_rawDescOnce.Do(func() {
		file_easyvirt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_easyvirt_proto_rawDesc), len(file_easyvirt_proto_rawDesc)))
	})
	return file_easyvirt_proto_rawDescData
}

var file_easyvirt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_easyvirt_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_easyvirt_proto_goTypes = []any{
	(DiskDeviceType)(0),         // 0: DiskDeviceType
	(*Void)(nil),                // 1: Void
	(*DomainID)(nil),            // 2: DomainID
	(*DiskDescriptor)(nil),      // 3: DiskDescriptor
	(*NicDescriptor)(nil),       // 4: NicDescriptor
	(*VncDescriptor)(nil),       // 5: VncDescriptor
	(*VideoCardDescriptor)(nil), // 6: VideoCardDescriptor
	(*VM)(nil),                  // 7: VM
	(*CreateVMRequest)(nil),     // 8: CreateVMRequest
	(*GetVMRequest)(nil),        // 9: GetVMRequest
	(*GetVMResponse)(nil),       // 10: GetVMResponse
	(*ListVMsRequest)(nil),      // 11: ListVMsRequest
	(*ListVMsResponse)(nil),     // 12: ListVMsResponse
	(*StartVMRequest)(nil),      // 13: StartVMRequest
	(*StopVMRequest)(nil),       // 14: StopVMRequest
	(*RestartVMRequest)(nil),    // 15: RestartVMRequest
	(*PauseVMRequest)(nil),      // 16: PauseVMRequest
	(*ResumeVMRequest)(nil),     // 17: ResumeVMRequest
	(*DeleteVMRequest)(nil),     // 18: DeleteVMRequest
	(*UpdateVMRequest)(nil),     // 19: UpdateVMRequest
}
var file_easyvirt_proto_depIdxs = []int32{
	0,  // 0: DiskDescriptor.device_type:type_name -> DiskDeviceType
	2,  // 1: VM.domain_id:type_name -> DomainID
	3,  // 2: VM.disk_list:type_name -> DiskDescriptor
	4,  // 3: VM.nic_list:type_name -> NicDescriptor
	5,  // 4: VM.vnc_list:type_name -> VncDescriptor
	6,  // 5: VM.video_card_list:type_name -> VideoCardDescriptor
	7,  // 6: CreateVMRequest.vm:type_name -> VM
	2,  // 7: GetVMRequest.domain:type_name -> DomainID
	7,  // 8: GetVMResponse.vm:type_name -> VM
	7,  // 9: ListVMsResponse.vms:type_name -> VM
	2,  // 10: StartVMRequest.domain:type_name -> DomainID
	2,  // 11: StopVMRequest.domain:type_name -> DomainID
	2,  // 12: RestartVMRequest.domain:type_name -> DomainID
	2,  // 13: PauseVMRequest.domain:type_name -> DomainID
	2,  // 14: ResumeVMRequest.domain:type_name -> DomainID
	2,  // 15: DeleteVMRequest.domain:type_name -> DomainID
	2,  // 16: UpdateVMRequest.domain:type_name -> DomainID
	8,  // 17: EasyVirt.CreateVM:input_type -> CreateVMRequest
	18, // 18: EasyVirt.DeleteVM:input_type -> DeleteVMRequest
	19, // 19: EasyVirt.UpdateVM:input_type -> UpdateVMRequest
	9,  // 20: EasyVirt.GetVM:input_type -> GetVMRequest
	11, // 21: EasyVirt.ListVMs:input_type -> ListVMsRequest
	13, // 22: EasyVirt.StartVM:input_type -> StartVMRequest
	14, // 23: EasyVirt.StopVM:input_type -> StopVMRequest
	15, // 24: EasyVirt.RestartVM:input_type -> RestartVMRequest
	16, // 25: EasyVirt.SuspendVM:input_type -> PauseVMRequest
	17, // 26: EasyVirt.ResumeVM:input_type -> ResumeVMRequest
	1,  // 27: EasyVirt.CreateVM:output_type -> Void
	1,  // 28: EasyVirt.DeleteVM:output_type -> Void
	1,  // 29: EasyVirt.UpdateVM:output_type -> Void
	10, // 30: EasyVirt.GetVM:output_type -> GetVMResponse
	12, // 31: EasyVirt.ListVMs:output_type -> ListVMsResponse
	1,  // 32: EasyVirt.StartVM:output_type -> Void
	1,  // 33: EasyVirt.StopVM:output_type -> Void
	1,  // 34: EasyVirt.RestartVM:output_type -> Void
	1,  // 35: EasyVirt.SuspendVM:output_type -> Void
	1,  // 36: EasyVirt.ResumeVM:output_type -> Void
	27, // [27:37] is the sub-list for method output_type
	17, // [17:27] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_easyvirt_proto_init() }
func file_easyvirt_proto_init() {
	if File_easyvirt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_easyvirt_proto_rawDesc), len(file_easyvirt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_easyvirt_proto_goTypes,
		DependencyIndexes: file_easyvirt_proto_depIdxs,
		EnumInfos:         file_easyvirt_proto_enumTypes,
		MessageInfos:      file_easyvirt_proto_msgTypes,
	}.Build()
	File_easyvirt_proto = out.File
	file_easyvirt_proto_goTypes = nil
	file_easyvirt_proto_depIdxs = nil
}
