// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: virt.proto

package domain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TinyVirt_CreateVM_FullMethodName  = "/TinyVirt/CreateVM"
	TinyVirt_DeleteVM_FullMethodName  = "/TinyVirt/DeleteVM"
	TinyVirt_UpdateVM_FullMethodName  = "/TinyVirt/UpdateVM"
	TinyVirt_GetVM_FullMethodName     = "/TinyVirt/GetVM"
	TinyVirt_ListVMs_FullMethodName   = "/TinyVirt/ListVMs"
	TinyVirt_StartVM_FullMethodName   = "/TinyVirt/StartVM"
	TinyVirt_StopVM_FullMethodName    = "/TinyVirt/StopVM"
	TinyVirt_RestartVM_FullMethodName = "/TinyVirt/RestartVM"
	TinyVirt_SuspendVM_FullMethodName = "/TinyVirt/SuspendVM"
	TinyVirt_ResumeVM_FullMethodName  = "/TinyVirt/ResumeVM"
)

// TinyVirtClient is the client API for TinyVirt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TinyVirtClient interface {
	// domain CRUD
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*Void, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*Void, error)
	UpdateVM(ctx context.Context, in *UpdateVMRequest, opts ...grpc.CallOption) (*Void, error)
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error)
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// operations
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*Void, error)
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*Void, error)
	RestartVM(ctx context.Context, in *RestartVMRequest, opts ...grpc.CallOption) (*Void, error)
	SuspendVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*Void, error)
	ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*Void, error)
}

type tinyVirtClient struct {
	cc grpc.ClientConnInterface
}

func NewTinyVirtClient(cc grpc.ClientConnInterface) TinyVirtClient {
	return &tinyVirtClient{cc}
}

func (c *tinyVirtClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) UpdateVM(ctx context.Context, in *UpdateVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_UpdateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMResponse)
	err := c.cc.Invoke(ctx, TinyVirt_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, TinyVirt_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) RestartVM(ctx context.Context, in *RestartVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_RestartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) SuspendVM(ctx context.Context, in *PauseVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_SuspendVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tinyVirtClient) ResumeVM(ctx context.Context, in *ResumeVMRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, TinyVirt_ResumeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TinyVirtServer is the server API for TinyVirt service.
// All implementations must embed UnimplementedTinyVirtServer
// for forward compatibility.
type TinyVirtServer interface {
	// domain CRUD
	CreateVM(context.Context, *CreateVMRequest) (*Void, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*Void, error)
	UpdateVM(context.Context, *UpdateVMRequest) (*Void, error)
	GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	// operations
	StartVM(context.Context, *StartVMRequest) (*Void, error)
	StopVM(context.Context, *StopVMRequest) (*Void, error)
	RestartVM(context.Context, *RestartVMRequest) (*Void, error)
	SuspendVM(context.Context, *PauseVMRequest) (*Void, error)
	ResumeVM(context.Context, *ResumeVMRequest) (*Void, error)
	mustEmbedUnimplementedTinyVirtServer()
}

// UnimplementedTinyVirtServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTinyVirtServer struct{}

func (UnimplementedTinyVirtServer) CreateVM(context.Context, *CreateVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedTinyVirtServer) DeleteVM(context.Context, *DeleteVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedTinyVirtServer) UpdateVM(context.Context, *UpdateVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVM not implemented")
}
func (UnimplementedTinyVirtServer) GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedTinyVirtServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedTinyVirtServer) StartVM(context.Context, *StartVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedTinyVirtServer) StopVM(context.Context, *StopVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedTinyVirtServer) RestartVM(context.Context, *RestartVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartVM not implemented")
}
func (UnimplementedTinyVirtServer) SuspendVM(context.Context, *PauseVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendVM not implemented")
}
func (UnimplementedTinyVirtServer) ResumeVM(context.Context, *ResumeVMRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeVM not implemented")
}
func (UnimplementedTinyVirtServer) mustEmbedUnimplementedTinyVirtServer() {}
func (UnimplementedTinyVirtServer) testEmbeddedByValue()                  {}

// UnsafeTinyVirtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TinyVirtServer will
// result in compilation errors.
type UnsafeTinyVirtServer interface {
	mustEmbedUnimplementedTinyVirtServer()
}

func RegisterTinyVirtServer(s grpc.ServiceRegistrar, srv TinyVirtServer) {
	// If the following call pancis, it indicates UnimplementedTinyVirtServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TinyVirt_ServiceDesc, srv)
}

func _TinyVirt_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_UpdateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).UpdateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_UpdateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).UpdateVM(ctx, req.(*UpdateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_RestartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).RestartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_RestartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).RestartVM(ctx, req.(*RestartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_SuspendVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).SuspendVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_SuspendVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).SuspendVM(ctx, req.(*PauseVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TinyVirt_ResumeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TinyVirtServer).ResumeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TinyVirt_ResumeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TinyVirtServer).ResumeVM(ctx, req.(*ResumeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TinyVirt_ServiceDesc is the grpc.ServiceDesc for TinyVirt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TinyVirt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TinyVirt",
	HandlerType: (*TinyVirtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _TinyVirt_CreateVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _TinyVirt_DeleteVM_Handler,
		},
		{
			MethodName: "UpdateVM",
			Handler:    _TinyVirt_UpdateVM_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _TinyVirt_GetVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _TinyVirt_ListVMs_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _TinyVirt_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _TinyVirt_StopVM_Handler,
		},
		{
			MethodName: "RestartVM",
			Handler:    _TinyVirt_RestartVM_Handler,
		},
		{
			MethodName: "SuspendVM",
			Handler:    _TinyVirt_SuspendVM_Handler,
		},
		{
			MethodName: "ResumeVM",
			Handler:    _TinyVirt_ResumeVM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "virt.proto",
}
