// Code generated by ent, DO NOT EDIT.

package disk

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the disk type in the database.
	Label = "disk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFormat holds the string denoting the format field in the database.
	FieldFormat = "format"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSizeGB holds the string denoting the size_gb field in the database.
	FieldSizeGB = "size_gb"
	// Table holds the table name of the disk in the database.
	Table = "disks"
)

// Columns holds all SQL columns for disk fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldFormat,
	FieldDescription,
	FieldSizeGB,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// FormatValidator is a validator for the "format" field. It is called by the builders before save.
	FormatValidator func(string) error
	// SizeGBValidator is a validator for the "size_gb" field. It is called by the builders before save.
	SizeGBValidator func(uint32) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Disk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFormat orders the results by the format field.
func ByFormat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormat, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySizeGB orders the results by the size_gb field.
func BySizeGB(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeGB, opts...).ToFunc()
}
