// Code generated by ent, DO NOT EDIT.

package disk

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tinyvirt/tinyvirt/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldName, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldFormat, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldDescription, v))
}

// SizeGB applies equality check predicate on the "size_gb" field. It's identical to SizeGBEQ.
func SizeGB(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldSizeGB, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContainsFold(FieldName, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContainsFold(FieldFormat, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Disk {
	return predicate.Disk(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Disk {
	return predicate.Disk(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Disk {
	return predicate.Disk(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Disk {
	return predicate.Disk(sql.FieldContainsFold(FieldDescription, v))
}

// SizeGBEQ applies the EQ predicate on the "size_gb" field.
func SizeGBEQ(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldEQ(FieldSizeGB, v))
}

// SizeGBNEQ applies the NEQ predicate on the "size_gb" field.
func SizeGBNEQ(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldNEQ(FieldSizeGB, v))
}

// SizeGBIn applies the In predicate on the "size_gb" field.
func SizeGBIn(vs ...uint32) predicate.Disk {
	return predicate.Disk(sql.FieldIn(FieldSizeGB, vs...))
}

// SizeGBNotIn applies the NotIn predicate on the "size_gb" field.
func SizeGBNotIn(vs ...uint32) predicate.Disk {
	return predicate.Disk(sql.FieldNotIn(FieldSizeGB, vs...))
}

// SizeGBGT applies the GT predicate on the "size_gb" field.
func SizeGBGT(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldGT(FieldSizeGB, v))
}

// SizeGBGTE applies the GTE predicate on the "size_gb" field.
func SizeGBGTE(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldGTE(FieldSizeGB, v))
}

// SizeGBLT applies the LT predicate on the "size_gb" field.
func SizeGBLT(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldLT(FieldSizeGB, v))
}

// SizeGBLTE applies the LTE predicate on the "size_gb" field.
func SizeGBLTE(v uint32) predicate.Disk {
	return predicate.Disk(sql.FieldLTE(FieldSizeGB, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Disk) predicate.Disk {
	return predicate.Disk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Disk) predicate.Disk {
	return predicate.Disk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Disk) predicate.Disk {
	return predicate.Disk(sql.NotPredicates(p))
}
