// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DisksColumns holds the columns for the "disks" table.
	DisksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "format", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "size_gb", Type: field.TypeUint32},
	}
	// DisksTable holds the schema information for the "disks" table.
	DisksTable = &schema.Table{
		Name:       "disks",
		Columns:    DisksColumns,
		PrimaryKey: []*schema.Column{DisksColumns[0]},
	}
	// VmsColumns holds the columns for the "vms" table.
	VmsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// VmsTable holds the schema information for the "vms" table.
	VmsTable = &schema.Table{
		Name:       "vms",
		Columns:    VmsColumns,
		PrimaryKey: []*schema.Column{VmsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DisksTable,
		VmsTable,
	}
)

func init() {
}
