// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/easyvirt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_proto_easyvirt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{0}
}

type DomainID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainID) Reset() {
	*x = DomainID{}
	mi := &file_proto_easyvirt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainID) ProtoMessage() {}

func (x *DomainID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainID.ProtoReflect.Descriptor instead.
func (*DomainID) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{1}
}

func (x *DomainID) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DomainID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DiskDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskDescriptor) Reset() {
	*x = DiskDescriptor{}
	mi := &file_proto_easyvirt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskDescriptor) ProtoMessage() {}

func (x *DiskDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskDescriptor.ProtoReflect.Descriptor instead.
func (*DiskDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{2}
}

func (x *DiskDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiskDescriptor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type NicDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NicDescriptor) Reset() {
	*x = NicDescriptor{}
	mi := &file_proto_easyvirt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NicDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NicDescriptor) ProtoMessage() {}

func (x *NicDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NicDescriptor.ProtoReflect.Descriptor instead.
func (*NicDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{3}
}

type CdromDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CdromDescriptor) Reset() {
	*x = CdromDescriptor{}
	mi := &file_proto_easyvirt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CdromDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CdromDescriptor) ProtoMessage() {}

func (x *CdromDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CdromDescriptor.ProtoReflect.Descriptor instead.
func (*CdromDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{4}
}

type VncDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VncDescriptor) Reset() {
	*x = VncDescriptor{}
	mi := &file_proto_easyvirt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VncDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VncDescriptor) ProtoMessage() {}

func (x *VncDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VncDescriptor.ProtoReflect.Descriptor instead.
func (*VncDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{5}
}

type VideoCardDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoCardDescriptor) Reset() {
	*x = VideoCardDescriptor{}
	mi := &file_proto_easyvirt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoCardDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoCardDescriptor) ProtoMessage() {}

func (x *VideoCardDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoCardDescriptor.ProtoReflect.Descriptor instead.
func (*VideoCardDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{6}
}

type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Descriptor_:
	//
	//	*Device_Disk
	//	*Device_Nic
	//	*Device_Cdrom
	//	*Device_Vnc
	//	*Device_VideoCard
	Descriptor_   isDevice_Descriptor_ `protobuf_oneof:"descriptor"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_easyvirt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{7}
}

func (x *Device) GetDescriptor_() isDevice_Descriptor_ {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Device) GetDisk() *DiskDescriptor {
	if x != nil {
		if x, ok := x.Descriptor_.(*Device_Disk); ok {
			return x.Disk
		}
	}
	return nil
}

func (x *Device) GetNic() *NicDescriptor {
	if x != nil {
		if x, ok := x.Descriptor_.(*Device_Nic); ok {
			return x.Nic
		}
	}
	return nil
}

func (x *Device) GetCdrom() *CdromDescriptor {
	if x != nil {
		if x, ok := x.Descriptor_.(*Device_Cdrom); ok {
			return x.Cdrom
		}
	}
	return nil
}

func (x *Device) GetVnc() *VncDescriptor {
	if x != nil {
		if x, ok := x.Descriptor_.(*Device_Vnc); ok {
			return x.Vnc
		}
	}
	return nil
}

func (x *Device) GetVideoCard() *VideoCardDescriptor {
	if x != nil {
		if x, ok := x.Descriptor_.(*Device_VideoCard); ok {
			return x.VideoCard
		}
	}
	return nil
}

type isDevice_Descriptor_ interface {
	isDevice_Descriptor_()
}

type Device_Disk struct {
	Disk *DiskDescriptor `protobuf:"bytes,10,opt,name=disk,proto3,oneof"`
}

type Device_Nic struct {
	Nic *NicDescriptor `protobuf:"bytes,11,opt,name=nic,proto3,oneof"`
}

type Device_Cdrom struct {
	Cdrom *CdromDescriptor `protobuf:"bytes,13,opt,name=cdrom,proto3,oneof"`
}

type Device_Vnc struct {
	Vnc *VncDescriptor `protobuf:"bytes,14,opt,name=vnc,proto3,oneof"`
}

type Device_VideoCard struct {
	VideoCard *VideoCardDescriptor `protobuf:"bytes,15,opt,name=video_card,json=videoCard,proto3,oneof"`
}

func (*Device_Disk) isDevice_Descriptor_() {}

func (*Device_Nic) isDevice_Descriptor_() {}

func (*Device_Cdrom) isDevice_Descriptor_() {}

func (*Device_Vnc) isDevice_Descriptor_() {}

func (*Device_VideoCard) isDevice_Descriptor_() {}

type VM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DomainId      *DomainID              `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	VcpuCount     uint32                 `protobuf:"varint,2,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	Memory        uint32                 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	BootDevices   []string               `protobuf:"bytes,10,rep,name=boot_devices,json=bootDevices,proto3" json:"boot_devices,omitempty"`
	Devices       []*Device              `protobuf:"bytes,11,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VM) Reset() {
	*x = VM{}
	mi := &file_proto_easyvirt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VM) ProtoMessage() {}

func (x *VM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VM.ProtoReflect.Descriptor instead.
func (*VM) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{8}
}

func (x *VM) GetDomainId() *DomainID {
	if x != nil {
		return x.DomainId
	}
	return nil
}

func (x *VM) GetVcpuCount() uint32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *VM) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *VM) GetBootDevices() []string {
	if x != nil {
		return x.BootDevices
	}
	return nil
}

func (x *VM) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VM                    `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVMRequest) GetVm() *VM {
	if x != nil {
		return x.Vm
	}
	return nil
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{10}
}

func (x *GetVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type GetVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VM                    `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMResponse) Reset() {
	*x = GetVMResponse{}
	mi := &file_proto_easyvirt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMResponse) ProtoMessage() {}

func (x *GetVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMResponse.ProtoReflect.Descriptor instead.
func (*GetVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{11}
}

func (x *GetVMResponse) GetVm() *VM {
	if x != nil {
		return x.Vm
	}
	return nil
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Inactive      bool                   `protobuf:"varint,2,opt,name=inactive,proto3" json:"inactive,omitempty"`
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{12}
}

func (x *ListVMsRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ListVMsRequest) GetInactive() bool {
	if x != nil {
		return x.Inactive
	}
	return false
}

func (x *ListVMsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VM                  `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_proto_easyvirt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{13}
}

func (x *ListVMsResponse) GetVms() []*VM {
	if x != nil {
		return x.Vms
	}
	return nil
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{14}
}

func (x *StartVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type StopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // destory domain or not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{15}
}

func (x *StopVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *StopVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RestartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartVMRequest) Reset() {
	*x = RestartVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVMRequest) ProtoMessage() {}

func (x *RestartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartVMRequest.ProtoReflect.Descriptor instead.
func (*RestartVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{16}
}

func (x *RestartVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RestartVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PauseVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVMRequest) Reset() {
	*x = PauseVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVMRequest) ProtoMessage() {}

func (x *PauseVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVMRequest.ProtoReflect.Descriptor instead.
func (*PauseVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{17}
}

func (x *PauseVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ResumeVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVMRequest) Reset() {
	*x = ResumeVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVMRequest) ProtoMessage() {}

func (x *ResumeVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVMRequest.ProtoReflect.Descriptor instead.
func (*ResumeVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{18}
}

func (x *ResumeVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DeleteDisks   bool                   `protobuf:"varint,2,opt,name=delete_disks,json=deleteDisks,proto3" json:"delete_disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *DeleteVMRequest) GetDeleteDisks() bool {
	if x != nil {
		return x.DeleteDisks
	}
	return false
}

type UpdateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *DomainID              `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVMRequest) Reset() {
	*x = UpdateVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVMRequest) ProtoMessage() {}

func (x *UpdateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVMRequest.ProtoReflect.Descriptor instead.
func (*UpdateVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateVMRequest) GetDomain() *DomainID {
	if x != nil {
		return x.Domain
	}
	return nil
}

var File_proto_easyvirt_proto protoreflect.FileDescriptor

const file_proto_easyvirt_proto_rawDesc = "" +
	"\n" +
	"\x14proto/easyvirt.proto\"\x06\n" +
	"\x04Void\"B\n" +
	"\bDomainID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"8\n" +
	"\x0eDiskDescriptor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x0f\n" +
	"\rNicDescriptor\"\x11\n" +
	"\x0fCdromDescriptor\"\x0f\n" +
	"\rVncDescriptor\"\x15\n" +
	"\x13VideoCardDescriptor\"\xe6\x01\n" +
	"\x06Device\x12%\n" +
	"\x04disk\x18\n" +
	" \x01(\v2\x0f.DiskDescriptorH\x00R\x04disk\x12\"\n" +
	"\x03nic\x18\v \x01(\v2\x0e.NicDescriptorH\x00R\x03nic\x12(\n" +
	"\x05cdrom\x18\r \x01(\v2\x10.CdromDescriptorH\x00R\x05cdrom\x12\"\n" +
	"\x03vnc\x18\x0e \x01(\v2\x0e.VncDescriptorH\x00R\x03vnc\x125\n" +
	"\n" +
	"video_card\x18\x0f \x01(\v2\x14.VideoCardDescriptorH\x00R\tvideoCardB\f\n" +
	"\n" +
	"descriptor\"\xa9\x01\n" +
	"\x02VM\x12&\n" +
	"\tdomain_id\x18\x01 \x01(\v2\t.DomainIDR\bdomainId\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x02 \x01(\rR\tvcpuCount\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\rR\x06memory\x12!\n" +
	"\fboot_devices\x18\n" +
	" \x03(\tR\vbootDevices\x12!\n" +
	"\adevices\x18\v \x03(\v2\a.DeviceR\adevices\"&\n" +
	"\x0fCreateVMRequest\x12\x13\n" +
	"\x02vm\x18\x01 \x01(\v2\x03.VMR\x02vm\"1\n" +
	"\fGetVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"$\n" +
	"\rGetVMResponse\x12\x13\n" +
	"\x02vm\x18\x01 \x01(\v2\x03.VMR\x02vm\"V\n" +
	"\x0eListVMsRequest\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1a\n" +
	"\binactive\x18\x02 \x01(\bR\binactive\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"(\n" +
	"\x0fListVMsResponse\x12\x15\n" +
	"\x03vms\x18\x01 \x03(\v2\x03.VMR\x03vms\"3\n" +
	"\x0eStartVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"H\n" +
	"\rStopVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"K\n" +
	"\x10RestartVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"3\n" +
	"\x0ePauseVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"4\n" +
	"\x0fResumeVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\"W\n" +
	"\x0fDeleteVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain\x12!\n" +
	"\fdelete_disks\x18\x02 \x01(\bR\vdeleteDisks\"4\n" +
	"\x0fUpdateVMRequest\x12!\n" +
	"\x06domain\x18\x01 \x01(\v2\t.DomainIDR\x06domain2\x98\x03\n" +
	"\bEasyVirt\x12%\n" +
	"\bCreateVM\x12\x10.CreateVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bDeleteVM\x12\x10.DeleteVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bUpdateVM\x12\x10.UpdateVMRequest\x1a\x05.Void\"\x00\x12(\n" +
	"\x05GetVM\x12\r.GetVMRequest\x1a\x0e.GetVMResponse\"\x00\x12.\n" +
	"\aListVMs\x12\x0f.ListVMsRequest\x1a\x10.ListVMsResponse\"\x00\x12#\n" +
	"\aStartVM\x12\x0f.StartVMRequest\x1a\x05.Void\"\x00\x12!\n" +
	"\x06StopVM\x12\x0e.StopVMRequest\x1a\x05.Void\"\x00\x12'\n" +
	"\tRestartVM\x12\x11.RestartVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\tSuspendVM\x12\x0f.PauseVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bResumeVM\x12\x10.ResumeVMRequest\x1a\x05.Void\"\x00B%Z#github.com/fanyang89/easyvirt/protob\x06proto3"

var (
	file_proto_easyvirt_proto_rawDescOnce sync.Once
	file_proto_easyvirt_proto_rawDescData []byte
)

func file_proto_easyvirt_proto_rawDescGZIP() []byte {
	file_proto_easyvirt_proto_rawDescOnce.Do(func() {
		file_proto_easyvirt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_easyvirt_proto_rawDesc), len(file_proto_easyvirt_proto_rawDesc)))
	})
	return file_proto_easyvirt_proto_rawDescData
}

var file_proto_easyvirt_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_easyvirt_proto_goTypes = []any{
	(*Void)(nil),                // 0: Void
	(*DomainID)(nil),            // 1: DomainID
	(*DiskDescriptor)(nil),      // 2: DiskDescriptor
	(*NicDescriptor)(nil),       // 3: NicDescriptor
	(*CdromDescriptor)(nil),     // 4: CdromDescriptor
	(*VncDescriptor)(nil),       // 5: VncDescriptor
	(*VideoCardDescriptor)(nil), // 6: VideoCardDescriptor
	(*Device)(nil),              // 7: Device
	(*VM)(nil),                  // 8: VM
	(*CreateVMRequest)(nil),     // 9: CreateVMRequest
	(*GetVMRequest)(nil),        // 10: GetVMRequest
	(*GetVMResponse)(nil),       // 11: GetVMResponse
	(*ListVMsRequest)(nil),      // 12: ListVMsRequest
	(*ListVMsResponse)(nil),     // 13: ListVMsResponse
	(*StartVMRequest)(nil),      // 14: StartVMRequest
	(*StopVMRequest)(nil),       // 15: StopVMRequest
	(*RestartVMRequest)(nil),    // 16: RestartVMRequest
	(*PauseVMRequest)(nil),      // 17: PauseVMRequest
	(*ResumeVMRequest)(nil),     // 18: ResumeVMRequest
	(*DeleteVMRequest)(nil),     // 19: DeleteVMRequest
	(*UpdateVMRequest)(nil),     // 20: UpdateVMRequest
}
var file_proto_easyvirt_proto_depIdxs = []int32{
	2,  // 0: Device.disk:type_name -> DiskDescriptor
	3,  // 1: Device.nic:type_name -> NicDescriptor
	4,  // 2: Device.cdrom:type_name -> CdromDescriptor
	5,  // 3: Device.vnc:type_name -> VncDescriptor
	6,  // 4: Device.video_card:type_name -> VideoCardDescriptor
	1,  // 5: VM.domain_id:type_name -> DomainID
	7,  // 6: VM.devices:type_name -> Device
	8,  // 7: CreateVMRequest.vm:type_name -> VM
	1,  // 8: GetVMRequest.domain:type_name -> DomainID
	8,  // 9: GetVMResponse.vm:type_name -> VM
	8,  // 10: ListVMsResponse.vms:type_name -> VM
	1,  // 11: StartVMRequest.domain:type_name -> DomainID
	1,  // 12: StopVMRequest.domain:type_name -> DomainID
	1,  // 13: RestartVMRequest.domain:type_name -> DomainID
	1,  // 14: PauseVMRequest.domain:type_name -> DomainID
	1,  // 15: ResumeVMRequest.domain:type_name -> DomainID
	1,  // 16: DeleteVMRequest.domain:type_name -> DomainID
	1,  // 17: UpdateVMRequest.domain:type_name -> DomainID
	9,  // 18: EasyVirt.CreateVM:input_type -> CreateVMRequest
	19, // 19: EasyVirt.DeleteVM:input_type -> DeleteVMRequest
	20, // 20: EasyVirt.UpdateVM:input_type -> UpdateVMRequest
	10, // 21: EasyVirt.GetVM:input_type -> GetVMRequest
	12, // 22: EasyVirt.ListVMs:input_type -> ListVMsRequest
	14, // 23: EasyVirt.StartVM:input_type -> StartVMRequest
	15, // 24: EasyVirt.StopVM:input_type -> StopVMRequest
	16, // 25: EasyVirt.RestartVM:input_type -> RestartVMRequest
	17, // 26: EasyVirt.SuspendVM:input_type -> PauseVMRequest
	18, // 27: EasyVirt.ResumeVM:input_type -> ResumeVMRequest
	0,  // 28: EasyVirt.CreateVM:output_type -> Void
	0,  // 29: EasyVirt.DeleteVM:output_type -> Void
	0,  // 30: EasyVirt.UpdateVM:output_type -> Void
	11, // 31: EasyVirt.GetVM:output_type -> GetVMResponse
	13, // 32: EasyVirt.ListVMs:output_type -> ListVMsResponse
	0,  // 33: EasyVirt.StartVM:output_type -> Void
	0,  // 34: EasyVirt.StopVM:output_type -> Void
	0,  // 35: EasyVirt.RestartVM:output_type -> Void
	0,  // 36: EasyVirt.SuspendVM:output_type -> Void
	0,  // 37: EasyVirt.ResumeVM:output_type -> Void
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_easyvirt_proto_init() }
func file_proto_easyvirt_proto_init() {
	if File_proto_easyvirt_proto != nil {
		return
	}
	file_proto_easyvirt_proto_msgTypes[7].OneofWrappers = []any{
		(*Device_Disk)(nil),
		(*Device_Nic)(nil),
		(*Device_Cdrom)(nil),
		(*Device_Vnc)(nil),
		(*Device_VideoCard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_easyvirt_proto_rawDesc), len(file_proto_easyvirt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_easyvirt_proto_goTypes,
		DependencyIndexes: file_proto_easyvirt_proto_depIdxs,
		MessageInfos:      file_proto_easyvirt_proto_msgTypes,
	}.Build()
	File_proto_easyvirt_proto = out.File
	file_proto_easyvirt_proto_goTypes = nil
	file_proto_easyvirt_proto_depIdxs = nil
}
