// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/easyvirt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VMState int32

const (
	VMState_VM_STATE_UNDEFINED   VMState = 0
	VMState_VM_STATE_NOSTATE     VMState = 1
	VMState_VM_STATE_RUNNING     VMState = 2
	VMState_VM_STATE_BLOCKED     VMState = 3
	VMState_VM_STATE_PAUSED      VMState = 4
	VMState_VM_STATE_SHUTDOWN    VMState = 5
	VMState_VM_STATE_SHUTOFF     VMState = 6
	VMState_VM_STATE_CRASHED     VMState = 7
	VMState_VM_STATE_PMSUSPENDED VMState = 8
)

// Enum value maps for VMState.
var (
	VMState_name = map[int32]string{
		0: "VM_STATE_UNDEFINED",
		1: "VM_STATE_NOSTATE",
		2: "VM_STATE_RUNNING",
		3: "VM_STATE_BLOCKED",
		4: "VM_STATE_PAUSED",
		5: "VM_STATE_SHUTDOWN",
		6: "VM_STATE_SHUTOFF",
		7: "VM_STATE_CRASHED",
		8: "VM_STATE_PMSUSPENDED",
	}
	VMState_value = map[string]int32{
		"VM_STATE_UNDEFINED":   0,
		"VM_STATE_NOSTATE":     1,
		"VM_STATE_RUNNING":     2,
		"VM_STATE_BLOCKED":     3,
		"VM_STATE_PAUSED":      4,
		"VM_STATE_SHUTDOWN":    5,
		"VM_STATE_SHUTOFF":     6,
		"VM_STATE_CRASHED":     7,
		"VM_STATE_PMSUSPENDED": 8,
	}
)

func (x VMState) Enum() *VMState {
	p := new(VMState)
	*p = x
	return p
}

func (x VMState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_easyvirt_proto_enumTypes[0].Descriptor()
}

func (VMState) Type() protoreflect.EnumType {
	return &file_proto_easyvirt_proto_enumTypes[0]
}

func (x VMState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMState.Descriptor instead.
func (VMState) EnumDescriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{0}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_proto_easyvirt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{0}
}

type VMConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	VcpuCount     int32                  `protobuf:"varint,4,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	Disks         []string               `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks      []string               `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	OsType        string                 `protobuf:"bytes,7,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	Arch          string                 `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	MachineType   string                 `protobuf:"bytes,9,opt,name=machine_type,json=machineType,proto3" json:"machine_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMConfig) Reset() {
	*x = VMConfig{}
	mi := &file_proto_easyvirt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMConfig) ProtoMessage() {}

func (x *VMConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMConfig.ProtoReflect.Descriptor instead.
func (*VMConfig) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{1}
}

func (x *VMConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VMConfig) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMConfig) GetVcpuCount() int32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *VMConfig) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VMConfig) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *VMConfig) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *VMConfig) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *VMConfig) GetMachineType() string {
	if x != nil {
		return x.MachineType
	}
	return ""
}

type VirtualMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	State         VMState                `protobuf:"varint,4,opt,name=state,proto3,enum=VMState" json:"state,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	VcpuCount     int32                  `protobuf:"varint,6,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	CpuTimeNs     int64                  `protobuf:"varint,7,opt,name=cpu_time_ns,json=cpuTimeNs,proto3" json:"cpu_time_ns,omitempty"`
	MaxMemoryKb   int64                  `protobuf:"varint,8,opt,name=max_memory_kb,json=maxMemoryKb,proto3" json:"max_memory_kb,omitempty"`
	UsedMemoryKb  int64                  `protobuf:"varint,9,opt,name=used_memory_kb,json=usedMemoryKb,proto3" json:"used_memory_kb,omitempty"`
	Networks      []string               `protobuf:"bytes,10,rep,name=networks,proto3" json:"networks,omitempty"`
	Disks         []string               `protobuf:"bytes,11,rep,name=disks,proto3" json:"disks,omitempty"`
	XmlConfig     string                 `protobuf:"bytes,12,opt,name=xml_config,json=xmlConfig,proto3" json:"xml_config,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachine) Reset() {
	*x = VirtualMachine{}
	mi := &file_proto_easyvirt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachine) ProtoMessage() {}

func (x *VirtualMachine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachine.ProtoReflect.Descriptor instead.
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualMachine) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtualMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachine) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VirtualMachine) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNDEFINED
}

func (x *VirtualMachine) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VirtualMachine) GetVcpuCount() int32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *VirtualMachine) GetCpuTimeNs() int64 {
	if x != nil {
		return x.CpuTimeNs
	}
	return 0
}

func (x *VirtualMachine) GetMaxMemoryKb() int64 {
	if x != nil {
		return x.MaxMemoryKb
	}
	return 0
}

func (x *VirtualMachine) GetUsedMemoryKb() int64 {
	if x != nil {
		return x.UsedMemoryKb
	}
	return 0
}

func (x *VirtualMachine) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *VirtualMachine) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VirtualMachine) GetXmlConfig() string {
	if x != nil {
		return x.XmlConfig
	}
	return ""
}

func (x *VirtualMachine) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VirtualMachine) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *VMConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XmlTemplate   string                 `protobuf:"bytes,2,opt,name=xml_template,json=xmlTemplate,proto3" json:"xml_template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVMRequest) GetConfig() *VMConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateVMRequest) GetXmlTemplate() string {
	if x != nil {
		return x.XmlTemplate
	}
	return ""
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Vm            *VirtualMachine        `protobuf:"bytes,3,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_proto_easyvirt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateVMResponse) GetVm() *VirtualMachine {
	if x != nil {
		return x.Vm
	}
	return nil
}

type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{5}
}

func (x *GetVMRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVMRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Vm            *VirtualMachine        `protobuf:"bytes,3,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMResponse) Reset() {
	*x = GetVMResponse{}
	mi := &file_proto_easyvirt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMResponse) ProtoMessage() {}

func (x *GetVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMResponse.ProtoReflect.Descriptor instead.
func (*GetVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{6}
}

func (x *GetVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVMResponse) GetVm() *VirtualMachine {
	if x != nil {
		return x.Vm
	}
	return nil
}

type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{7}
}

func (x *ListVMsRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Vms           []*VirtualMachine      `protobuf:"bytes,3,rep,name=vms,proto3" json:"vms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_proto_easyvirt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{8}
}

func (x *ListVMsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListVMsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListVMsResponse) GetVms() []*VirtualMachine {
	if x != nil {
		return x.Vms
	}
	return nil
}

type FindDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDomain) Reset() {
	*x = FindDomain{}
	mi := &file_proto_easyvirt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDomain) ProtoMessage() {}

func (x *FindDomain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDomain.ProtoReflect.Descriptor instead.
func (*FindDomain) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{9}
}

func (x *FindDomain) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindDomain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindDomain) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{10}
}

func (x *StartVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type StopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // destory domain or not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{11}
}

func (x *StopVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *StopVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RestartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartVMRequest) Reset() {
	*x = RestartVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartVMRequest) ProtoMessage() {}

func (x *RestartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartVMRequest.ProtoReflect.Descriptor instead.
func (*RestartVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{12}
}

func (x *RestartVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RestartVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type PauseVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseVMRequest) Reset() {
	*x = PauseVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseVMRequest) ProtoMessage() {}

func (x *PauseVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseVMRequest.ProtoReflect.Descriptor instead.
func (*PauseVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{13}
}

func (x *PauseVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ResumeVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeVMRequest) Reset() {
	*x = ResumeVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeVMRequest) ProtoMessage() {}

func (x *ResumeVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeVMRequest.ProtoReflect.Descriptor instead.
func (*ResumeVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DeleteDisks   bool                   `protobuf:"varint,2,opt,name=delete_disks,json=deleteDisks,proto3" json:"delete_disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *DeleteVMRequest) GetDeleteDisks() bool {
	if x != nil {
		return x.DeleteDisks
	}
	return false
}

type UpdateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *FindDomain            `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVMRequest) Reset() {
	*x = UpdateVMRequest{}
	mi := &file_proto_easyvirt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVMRequest) ProtoMessage() {}

func (x *UpdateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_easyvirt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVMRequest.ProtoReflect.Descriptor instead.
func (*UpdateVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_easyvirt_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateVMRequest) GetDomain() *FindDomain {
	if x != nil {
		return x.Domain
	}
	return nil
}

var File_proto_easyvirt_proto protoreflect.FileDescriptor

const file_proto_easyvirt_proto_rawDesc = "" +
	"\n" +
	"\x14proto/easyvirt.proto\"\x06\n" +
	"\x04Void\"\xf0\x01\n" +
	"\bVMConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x04 \x01(\x05R\tvcpuCount\x12\x14\n" +
	"\x05disks\x18\x05 \x03(\tR\x05disks\x12\x1a\n" +
	"\bnetworks\x18\x06 \x03(\tR\bnetworks\x12\x17\n" +
	"\aos_type\x18\a \x01(\tR\x06osType\x12\x12\n" +
	"\x04arch\x18\b \x01(\tR\x04arch\x12!\n" +
	"\fmachine_type\x18\t \x01(\tR\vmachineType\"\x9d\x03\n" +
	"\x0eVirtualMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x1e\n" +
	"\x05state\x18\x04 \x01(\x0e2\b.VMStateR\x05state\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x06 \x01(\x05R\tvcpuCount\x12\x1e\n" +
	"\vcpu_time_ns\x18\a \x01(\x03R\tcpuTimeNs\x12\"\n" +
	"\rmax_memory_kb\x18\b \x01(\x03R\vmaxMemoryKb\x12$\n" +
	"\x0eused_memory_kb\x18\t \x01(\x03R\fusedMemoryKb\x12\x1a\n" +
	"\bnetworks\x18\n" +
	" \x03(\tR\bnetworks\x12\x14\n" +
	"\x05disks\x18\v \x03(\tR\x05disks\x12\x1d\n" +
	"\n" +
	"xml_config\x18\f \x01(\tR\txmlConfig\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"W\n" +
	"\x0fCreateVMRequest\x12!\n" +
	"\x06config\x18\x01 \x01(\v2\t.VMConfigR\x06config\x12!\n" +
	"\fxml_template\x18\x02 \x01(\tR\vxmlTemplate\"g\n" +
	"\x10CreateVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x02vm\x18\x03 \x01(\v2\x0f.VirtualMachineR\x02vm\"F\n" +
	"\fGetVMRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"d\n" +
	"\rGetVMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\x02vm\x18\x03 \x01(\v2\x0f.VirtualMachineR\x02vm\"\"\n" +
	"\x0eListVMsRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\"h\n" +
	"\x0fListVMsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x03vms\x18\x03 \x03(\v2\x0f.VirtualMachineR\x03vms\"D\n" +
	"\n" +
	"FindDomain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"5\n" +
	"\x0eStartVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain\"J\n" +
	"\rStopVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"M\n" +
	"\x10RestartVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"5\n" +
	"\x0ePauseVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain\"6\n" +
	"\x0fResumeVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain\"Y\n" +
	"\x0fDeleteVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain\x12!\n" +
	"\fdelete_disks\x18\x02 \x01(\bR\vdeleteDisks\"6\n" +
	"\x0fUpdateVMRequest\x12#\n" +
	"\x06domain\x18\x01 \x01(\v2\v.FindDomainR\x06domain*\xd5\x01\n" +
	"\aVMState\x12\x16\n" +
	"\x12VM_STATE_UNDEFINED\x10\x00\x12\x14\n" +
	"\x10VM_STATE_NOSTATE\x10\x01\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x02\x12\x14\n" +
	"\x10VM_STATE_BLOCKED\x10\x03\x12\x13\n" +
	"\x0fVM_STATE_PAUSED\x10\x04\x12\x15\n" +
	"\x11VM_STATE_SHUTDOWN\x10\x05\x12\x14\n" +
	"\x10VM_STATE_SHUTOFF\x10\x06\x12\x14\n" +
	"\x10VM_STATE_CRASHED\x10\a\x12\x18\n" +
	"\x14VM_STATE_PMSUSPENDED\x10\b2\x98\x03\n" +
	"\bEasyVirt\x12%\n" +
	"\bCreateVM\x12\x10.CreateVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bDeleteVM\x12\x10.DeleteVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bUpdateVM\x12\x10.UpdateVMRequest\x1a\x05.Void\"\x00\x12(\n" +
	"\x05GetVM\x12\r.GetVMRequest\x1a\x0e.GetVMResponse\"\x00\x12.\n" +
	"\aListVMs\x12\x0f.ListVMsRequest\x1a\x10.ListVMsResponse\"\x00\x12#\n" +
	"\aStartVM\x12\x0f.StartVMRequest\x1a\x05.Void\"\x00\x12!\n" +
	"\x06StopVM\x12\x0e.StopVMRequest\x1a\x05.Void\"\x00\x12'\n" +
	"\tRestartVM\x12\x11.RestartVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\tSuspendVM\x12\x0f.PauseVMRequest\x1a\x05.Void\"\x00\x12%\n" +
	"\bResumeVM\x12\x10.ResumeVMRequest\x1a\x05.Void\"\x00B%Z#github.com/fanyang89/easyvirt/protob\x06proto3"

var (
	file_proto_easyvirt_proto_rawDescOnce sync.Once
	file_proto_easyvirt_proto_rawDescData []byte
)

func file_proto_easyvirt_proto_rawDescGZIP() []byte {
	file_proto_easyvirt_proto_rawDescOnce.Do(func() {
		file_proto_easyvirt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_easyvirt_proto_rawDesc), len(file_proto_easyvirt_proto_rawDesc)))
	})
	return file_proto_easyvirt_proto_rawDescData
}

var file_proto_easyvirt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_easyvirt_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_easyvirt_proto_goTypes = []any{
	(VMState)(0),             // 0: VMState
	(*Void)(nil),             // 1: Void
	(*VMConfig)(nil),         // 2: VMConfig
	(*VirtualMachine)(nil),   // 3: VirtualMachine
	(*CreateVMRequest)(nil),  // 4: CreateVMRequest
	(*CreateVMResponse)(nil), // 5: CreateVMResponse
	(*GetVMRequest)(nil),     // 6: GetVMRequest
	(*GetVMResponse)(nil),    // 7: GetVMResponse
	(*ListVMsRequest)(nil),   // 8: ListVMsRequest
	(*ListVMsResponse)(nil),  // 9: ListVMsResponse
	(*FindDomain)(nil),       // 10: FindDomain
	(*StartVMRequest)(nil),   // 11: StartVMRequest
	(*StopVMRequest)(nil),    // 12: StopVMRequest
	(*RestartVMRequest)(nil), // 13: RestartVMRequest
	(*PauseVMRequest)(nil),   // 14: PauseVMRequest
	(*ResumeVMRequest)(nil),  // 15: ResumeVMRequest
	(*DeleteVMRequest)(nil),  // 16: DeleteVMRequest
	(*UpdateVMRequest)(nil),  // 17: UpdateVMRequest
}
var file_proto_easyvirt_proto_depIdxs = []int32{
	0,  // 0: VirtualMachine.state:type_name -> VMState
	2,  // 1: CreateVMRequest.config:type_name -> VMConfig
	3,  // 2: CreateVMResponse.vm:type_name -> VirtualMachine
	3,  // 3: GetVMResponse.vm:type_name -> VirtualMachine
	3,  // 4: ListVMsResponse.vms:type_name -> VirtualMachine
	10, // 5: StartVMRequest.domain:type_name -> FindDomain
	10, // 6: StopVMRequest.domain:type_name -> FindDomain
	10, // 7: RestartVMRequest.domain:type_name -> FindDomain
	10, // 8: PauseVMRequest.domain:type_name -> FindDomain
	10, // 9: ResumeVMRequest.domain:type_name -> FindDomain
	10, // 10: DeleteVMRequest.domain:type_name -> FindDomain
	10, // 11: UpdateVMRequest.domain:type_name -> FindDomain
	4,  // 12: EasyVirt.CreateVM:input_type -> CreateVMRequest
	16, // 13: EasyVirt.DeleteVM:input_type -> DeleteVMRequest
	17, // 14: EasyVirt.UpdateVM:input_type -> UpdateVMRequest
	6,  // 15: EasyVirt.GetVM:input_type -> GetVMRequest
	8,  // 16: EasyVirt.ListVMs:input_type -> ListVMsRequest
	11, // 17: EasyVirt.StartVM:input_type -> StartVMRequest
	12, // 18: EasyVirt.StopVM:input_type -> StopVMRequest
	13, // 19: EasyVirt.RestartVM:input_type -> RestartVMRequest
	14, // 20: EasyVirt.SuspendVM:input_type -> PauseVMRequest
	15, // 21: EasyVirt.ResumeVM:input_type -> ResumeVMRequest
	1,  // 22: EasyVirt.CreateVM:output_type -> Void
	1,  // 23: EasyVirt.DeleteVM:output_type -> Void
	1,  // 24: EasyVirt.UpdateVM:output_type -> Void
	7,  // 25: EasyVirt.GetVM:output_type -> GetVMResponse
	9,  // 26: EasyVirt.ListVMs:output_type -> ListVMsResponse
	1,  // 27: EasyVirt.StartVM:output_type -> Void
	1,  // 28: EasyVirt.StopVM:output_type -> Void
	1,  // 29: EasyVirt.RestartVM:output_type -> Void
	1,  // 30: EasyVirt.SuspendVM:output_type -> Void
	1,  // 31: EasyVirt.ResumeVM:output_type -> Void
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_easyvirt_proto_init() }
func file_proto_easyvirt_proto_init() {
	if File_proto_easyvirt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_easyvirt_proto_rawDesc), len(file_proto_easyvirt_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_easyvirt_proto_goTypes,
		DependencyIndexes: file_proto_easyvirt_proto_depIdxs,
		EnumInfos:         file_proto_easyvirt_proto_enumTypes,
		MessageInfos:      file_proto_easyvirt_proto_msgTypes,
	}.Build()
	File_proto_easyvirt_proto = out.File
	file_proto_easyvirt_proto_goTypes = nil
	file_proto_easyvirt_proto_depIdxs = nil
}
