// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fanyang89/easyvirt/ent/disk"
	"github.com/google/uuid"
)

// DiskCreate is the builder for creating a Disk entity.
type DiskCreate struct {
	config
	mutation *DiskMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *DiskCreate) SetName(v string) *DiskCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFormat sets the "format" field.
func (_c *DiskCreate) SetFormat(v string) *DiskCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DiskCreate) SetDescription(v string) *DiskCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *DiskCreate) SetNillableDescription(v *string) *DiskCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSizeGB sets the "size_gb" field.
func (_c *DiskCreate) SetSizeGB(v uint32) *DiskCreate {
	_c.mutation.SetSizeGB(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DiskCreate) SetID(v uuid.UUID) *DiskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DiskCreate) SetNillableID(v *uuid.UUID) *DiskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DiskMutation object of the builder.
func (_c *DiskCreate) Mutation() *DiskMutation {
	return _c.mutation
}

// Save creates the Disk in the database.
func (_c *DiskCreate) Save(ctx context.Context) (*Disk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiskCreate) SaveX(ctx context.Context) *Disk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiskCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := disk.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiskCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Disk.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := disk.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Disk.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Format(); !ok {
		return &ValidationError{Name: "format", err: errors.New(`ent: missing required field "Disk.format"`)}
	}
	if v, ok := _c.mutation.Format(); ok {
		if err := disk.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "Disk.format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SizeGB(); !ok {
		return &ValidationError{Name: "size_gb", err: errors.New(`ent: missing required field "Disk.size_gb"`)}
	}
	if v, ok := _c.mutation.SizeGB(); ok {
		if err := disk.SizeGBValidator(v); err != nil {
			return &ValidationError{Name: "size_gb", err: fmt.Errorf(`ent: validator failed for field "Disk.size_gb": %w`, err)}
		}
	}
	return nil
}

func (_c *DiskCreate) sqlSave(ctx context.Context) (*Disk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiskCreate) createSpec() (*Disk, *sqlgraph.CreateSpec) {
	var (
		_node = &Disk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(disk.Table, sqlgraph.NewFieldSpec(disk.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(disk.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(disk.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(disk.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SizeGB(); ok {
		_spec.SetField(disk.FieldSizeGB, field.TypeUint32, value)
		_node.SizeGB = value
	}
	return _node, _spec
}

// DiskCreateBulk is the builder for creating many Disk entities in bulk.
type DiskCreateBulk struct {
	config
	err      error
	builders []*DiskCreate
}

// Save creates the Disk entities in the database.
func (_c *DiskCreateBulk) Save(ctx context.Context) ([]*Disk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Disk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiskCreateBulk) SaveX(ctx context.Context) []*Disk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
