// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fanyang89/easyvirt/ent/disk"
	"github.com/fanyang89/easyvirt/ent/predicate"
)

// DiskUpdate is the builder for updating Disk entities.
type DiskUpdate struct {
	config
	hooks    []Hook
	mutation *DiskMutation
}

// Where appends a list predicates to the DiskUpdate builder.
func (_u *DiskUpdate) Where(ps ...predicate.Disk) *DiskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DiskUpdate) SetName(v string) *DiskUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DiskUpdate) SetNillableName(v *string) *DiskUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFormat sets the "format" field.
func (_u *DiskUpdate) SetFormat(v string) *DiskUpdate {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *DiskUpdate) SetNillableFormat(v *string) *DiskUpdate {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DiskUpdate) SetDescription(v string) *DiskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DiskUpdate) SetNillableDescription(v *string) *DiskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DiskUpdate) ClearDescription() *DiskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetSizeGB sets the "size_gb" field.
func (_u *DiskUpdate) SetSizeGB(v uint32) *DiskUpdate {
	_u.mutation.ResetSizeGB()
	_u.mutation.SetSizeGB(v)
	return _u
}

// SetNillableSizeGB sets the "size_gb" field if the given value is not nil.
func (_u *DiskUpdate) SetNillableSizeGB(v *uint32) *DiskUpdate {
	if v != nil {
		_u.SetSizeGB(*v)
	}
	return _u
}

// AddSizeGB adds value to the "size_gb" field.
func (_u *DiskUpdate) AddSizeGB(v int32) *DiskUpdate {
	_u.mutation.AddSizeGB(v)
	return _u
}

// Mutation returns the DiskMutation object of the builder.
func (_u *DiskUpdate) Mutation() *DiskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiskUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := disk.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Disk.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := disk.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "Disk.format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeGB(); ok {
		if err := disk.SizeGBValidator(v); err != nil {
			return &ValidationError{Name: "size_gb", err: fmt.Errorf(`ent: validator failed for field "Disk.size_gb": %w`, err)}
		}
	}
	return nil
}

func (_u *DiskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(disk.Table, disk.Columns, sqlgraph.NewFieldSpec(disk.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(disk.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(disk.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(disk.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(disk.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SizeGB(); ok {
		_spec.SetField(disk.FieldSizeGB, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSizeGB(); ok {
		_spec.AddField(disk.FieldSizeGB, field.TypeUint32, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{disk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiskUpdateOne is the builder for updating a single Disk entity.
type DiskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiskMutation
}

// SetName sets the "name" field.
func (_u *DiskUpdateOne) SetName(v string) *DiskUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DiskUpdateOne) SetNillableName(v *string) *DiskUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFormat sets the "format" field.
func (_u *DiskUpdateOne) SetFormat(v string) *DiskUpdateOne {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *DiskUpdateOne) SetNillableFormat(v *string) *DiskUpdateOne {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DiskUpdateOne) SetDescription(v string) *DiskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DiskUpdateOne) SetNillableDescription(v *string) *DiskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *DiskUpdateOne) ClearDescription() *DiskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetSizeGB sets the "size_gb" field.
func (_u *DiskUpdateOne) SetSizeGB(v uint32) *DiskUpdateOne {
	_u.mutation.ResetSizeGB()
	_u.mutation.SetSizeGB(v)
	return _u
}

// SetNillableSizeGB sets the "size_gb" field if the given value is not nil.
func (_u *DiskUpdateOne) SetNillableSizeGB(v *uint32) *DiskUpdateOne {
	if v != nil {
		_u.SetSizeGB(*v)
	}
	return _u
}

// AddSizeGB adds value to the "size_gb" field.
func (_u *DiskUpdateOne) AddSizeGB(v int32) *DiskUpdateOne {
	_u.mutation.AddSizeGB(v)
	return _u
}

// Mutation returns the DiskMutation object of the builder.
func (_u *DiskUpdateOne) Mutation() *DiskMutation {
	return _u.mutation
}

// Where appends a list predicates to the DiskUpdate builder.
func (_u *DiskUpdateOne) Where(ps ...predicate.Disk) *DiskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiskUpdateOne) Select(field string, fields ...string) *DiskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Disk entity.
func (_u *DiskUpdateOne) Save(ctx context.Context) (*Disk, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiskUpdateOne) SaveX(ctx context.Context) *Disk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiskUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := disk.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Disk.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := disk.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "Disk.format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeGB(); ok {
		if err := disk.SizeGBValidator(v); err != nil {
			return &ValidationError{Name: "size_gb", err: fmt.Errorf(`ent: validator failed for field "Disk.size_gb": %w`, err)}
		}
	}
	return nil
}

func (_u *DiskUpdateOne) sqlSave(ctx context.Context) (_node *Disk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(disk.Table, disk.Columns, sqlgraph.NewFieldSpec(disk.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Disk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, disk.FieldID)
		for _, f := range fields {
			if !disk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != disk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(disk.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(disk.FieldFormat, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(disk.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(disk.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SizeGB(); ok {
		_spec.SetField(disk.FieldSizeGB, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSizeGB(); ok {
		_spec.AddField(disk.FieldSizeGB, field.TypeUint32, value)
	}
	_node = &Disk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{disk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
