// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/tinyvirt/tinyvirt/ent/disk"
	"github.com/tinyvirt/tinyvirt/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	diskFields := schema.Disk{}.Fields()
	_ = diskFields
	// diskDescName is the schema descriptor for name field.
	diskDescName := diskFields[1].Descriptor()
	// disk.NameValidator is a validator for the "name" field. It is called by the builders before save.
	disk.NameValidator = diskDescName.Validators[0].(func(string) error)
	// diskDescFormat is the schema descriptor for format field.
	diskDescFormat := diskFields[2].Descriptor()
	// disk.FormatValidator is a validator for the "format" field. It is called by the builders before save.
	disk.FormatValidator = diskDescFormat.Validators[0].(func(string) error)
	// diskDescSizeGB is the schema descriptor for size_gb field.
	diskDescSizeGB := diskFields[4].Descriptor()
	// disk.SizeGBValidator is a validator for the "size_gb" field. It is called by the builders before save.
	disk.SizeGBValidator = diskDescSizeGB.Validators[0].(func(uint32) error)
	// diskDescID is the schema descriptor for id field.
	diskDescID := diskFields[0].Descriptor()
	// disk.DefaultID holds the default value on creation for the id field.
	disk.DefaultID = diskDescID.Default.(func() uuid.UUID)
}
