// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: disk_manager.proto

package disk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiskManager_CreateDisk_FullMethodName = "/DiskManager/CreateDisk"
	DiskManager_DeleteDisk_FullMethodName = "/DiskManager/DeleteDisk"
	DiskManager_UpdateDisk_FullMethodName = "/DiskManager/UpdateDisk"
	DiskManager_ListDisk_FullMethodName   = "/DiskManager/ListDisk"
	DiskManager_GetDisk_FullMethodName    = "/DiskManager/GetDisk"
)

// DiskManagerClient is the client API for DiskManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiskManagerClient interface {
	CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*CreateDiskResponse, error)
	DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*Void, error)
	UpdateDisk(ctx context.Context, in *UpdateDiskRequest, opts ...grpc.CallOption) (*Void, error)
	ListDisk(ctx context.Context, in *ListDiskRequest, opts ...grpc.CallOption) (*ListDiskResponse, error)
	GetDisk(ctx context.Context, in *GetDiskRequest, opts ...grpc.CallOption) (*GetDiskResponse, error)
}

type diskManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewDiskManagerClient(cc grpc.ClientConnInterface) DiskManagerClient {
	return &diskManagerClient{cc}
}

func (c *diskManagerClient) CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*CreateDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiskResponse)
	err := c.cc.Invoke(ctx, DiskManager_CreateDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskManagerClient) DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, DiskManager_DeleteDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskManagerClient) UpdateDisk(ctx context.Context, in *UpdateDiskRequest, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, DiskManager_UpdateDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskManagerClient) ListDisk(ctx context.Context, in *ListDiskRequest, opts ...grpc.CallOption) (*ListDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiskResponse)
	err := c.cc.Invoke(ctx, DiskManager_ListDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diskManagerClient) GetDisk(ctx context.Context, in *GetDiskRequest, opts ...grpc.CallOption) (*GetDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiskResponse)
	err := c.cc.Invoke(ctx, DiskManager_GetDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiskManagerServer is the server API for DiskManager service.
// All implementations must embed UnimplementedDiskManagerServer
// for forward compatibility.
type DiskManagerServer interface {
	CreateDisk(context.Context, *CreateDiskRequest) (*CreateDiskResponse, error)
	DeleteDisk(context.Context, *DeleteDiskRequest) (*Void, error)
	UpdateDisk(context.Context, *UpdateDiskRequest) (*Void, error)
	ListDisk(context.Context, *ListDiskRequest) (*ListDiskResponse, error)
	GetDisk(context.Context, *GetDiskRequest) (*GetDiskResponse, error)
	mustEmbedUnimplementedDiskManagerServer()
}

// UnimplementedDiskManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiskManagerServer struct{}

func (UnimplementedDiskManagerServer) CreateDisk(context.Context, *CreateDiskRequest) (*CreateDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDisk not implemented")
}
func (UnimplementedDiskManagerServer) DeleteDisk(context.Context, *DeleteDiskRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDisk not implemented")
}
func (UnimplementedDiskManagerServer) UpdateDisk(context.Context, *UpdateDiskRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDisk not implemented")
}
func (UnimplementedDiskManagerServer) ListDisk(context.Context, *ListDiskRequest) (*ListDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDisk not implemented")
}
func (UnimplementedDiskManagerServer) GetDisk(context.Context, *GetDiskRequest) (*GetDiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDisk not implemented")
}
func (UnimplementedDiskManagerServer) mustEmbedUnimplementedDiskManagerServer() {}
func (UnimplementedDiskManagerServer) testEmbeddedByValue()                     {}

// UnsafeDiskManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiskManagerServer will
// result in compilation errors.
type UnsafeDiskManagerServer interface {
	mustEmbedUnimplementedDiskManagerServer()
}

func RegisterDiskManagerServer(s grpc.ServiceRegistrar, srv DiskManagerServer) {
	// If the following call pancis, it indicates UnimplementedDiskManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiskManager_ServiceDesc, srv)
}

func _DiskManager_CreateDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskManagerServer).CreateDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiskManager_CreateDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskManagerServer).CreateDisk(ctx, req.(*CreateDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskManager_DeleteDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskManagerServer).DeleteDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiskManager_DeleteDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskManagerServer).DeleteDisk(ctx, req.(*DeleteDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskManager_UpdateDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskManagerServer).UpdateDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiskManager_UpdateDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskManagerServer).UpdateDisk(ctx, req.(*UpdateDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskManager_ListDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskManagerServer).ListDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiskManager_ListDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskManagerServer).ListDisk(ctx, req.(*ListDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiskManager_GetDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiskManagerServer).GetDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiskManager_GetDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiskManagerServer).GetDisk(ctx, req.(*GetDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiskManager_ServiceDesc is the grpc.ServiceDesc for DiskManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiskManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DiskManager",
	HandlerType: (*DiskManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDisk",
			Handler:    _DiskManager_CreateDisk_Handler,
		},
		{
			MethodName: "DeleteDisk",
			Handler:    _DiskManager_DeleteDisk_Handler,
		},
		{
			MethodName: "UpdateDisk",
			Handler:    _DiskManager_UpdateDisk_Handler,
		},
		{
			MethodName: "ListDisk",
			Handler:    _DiskManager_ListDisk_Handler,
		},
		{
			MethodName: "GetDisk",
			Handler:    _DiskManager_GetDisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "disk_manager.proto",
}
