// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: disk_manager.proto

package disk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiskFormat int32

const (
	DiskFormat_raw   DiskFormat = 0
	DiskFormat_qcow2 DiskFormat = 1
)

// Enum value maps for DiskFormat.
var (
	DiskFormat_name = map[int32]string{
		0: "raw",
		1: "qcow2",
	}
	DiskFormat_value = map[string]int32{
		"raw":   0,
		"qcow2": 1,
	}
)

func (x DiskFormat) Enum() *DiskFormat {
	p := new(DiskFormat)
	*p = x
	return p
}

func (x DiskFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiskFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_disk_manager_proto_enumTypes[0].Descriptor()
}

func (DiskFormat) Type() protoreflect.EnumType {
	return &file_disk_manager_proto_enumTypes[0]
}

func (x DiskFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiskFormat.Descriptor instead.
func (DiskFormat) EnumDescriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{0}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_disk_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{0}
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	DiskName      string                 `protobuf:"bytes,2,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Format        DiskFormat             `protobuf:"varint,4,opt,name=format,proto3,enum=DiskFormat" json:"format,omitempty"`
	Size          uint32                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"` // GiB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_disk_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Disk) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *Disk) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

func (x *Disk) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Disk) GetFormat() DiskFormat {
	if x != nil {
		return x.Format
	}
	return DiskFormat_raw
}

func (x *Disk) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CreateDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disk          *Disk                  `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiskRequest) Reset() {
	*x = CreateDiskRequest{}
	mi := &file_disk_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiskRequest) ProtoMessage() {}

func (x *CreateDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiskRequest.ProtoReflect.Descriptor instead.
func (*CreateDiskRequest) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDiskRequest) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type CreateDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedDisk   *Disk                  `protobuf:"bytes,1,opt,name=created_disk,json=createdDisk,proto3" json:"created_disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiskResponse) Reset() {
	*x = CreateDiskResponse{}
	mi := &file_disk_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiskResponse) ProtoMessage() {}

func (x *CreateDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiskResponse.ProtoReflect.Descriptor instead.
func (*CreateDiskResponse) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDiskResponse) GetCreatedDisk() *Disk {
	if x != nil {
		return x.CreatedDisk
	}
	return nil
}

type DeleteDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiskRequest) Reset() {
	*x = DeleteDiskRequest{}
	mi := &file_disk_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiskRequest) ProtoMessage() {}

func (x *DeleteDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiskRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiskRequest) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDiskRequest) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

type UpdateDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disk          *Disk                  `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiskRequest) Reset() {
	*x = UpdateDiskRequest{}
	mi := &file_disk_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiskRequest) ProtoMessage() {}

func (x *UpdateDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiskRequest.ProtoReflect.Descriptor instead.
func (*UpdateDiskRequest) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDiskRequest) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type ListDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiskRequest) Reset() {
	*x = ListDiskRequest{}
	mi := &file_disk_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiskRequest) ProtoMessage() {}

func (x *ListDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiskRequest.ProtoReflect.Descriptor instead.
func (*ListDiskRequest) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{6}
}

type ListDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disk          []*Disk                `protobuf:"bytes,1,rep,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiskResponse) Reset() {
	*x = ListDiskResponse{}
	mi := &file_disk_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiskResponse) ProtoMessage() {}

func (x *ListDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiskResponse.ProtoReflect.Descriptor instead.
func (*ListDiskResponse) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ListDiskResponse) GetDisk() []*Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

type GetDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	DiskName      string                 `protobuf:"bytes,2,opt,name=disk_name,json=diskName,proto3" json:"disk_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskRequest) Reset() {
	*x = GetDiskRequest{}
	mi := &file_disk_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskRequest) ProtoMessage() {}

func (x *GetDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskRequest.ProtoReflect.Descriptor instead.
func (*GetDiskRequest) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{8}
}

func (x *GetDiskRequest) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *GetDiskRequest) GetDiskName() string {
	if x != nil {
		return x.DiskName
	}
	return ""
}

type GetDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disk          *Disk                  `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskResponse) Reset() {
	*x = GetDiskResponse{}
	mi := &file_disk_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskResponse) ProtoMessage() {}

func (x *GetDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disk_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskResponse.ProtoReflect.Descriptor instead.
func (*GetDiskResponse) Descriptor() ([]byte, []int) {
	return file_disk_manager_proto_rawDescGZIP(), []int{9}
}

func (x *GetDiskResponse) GetDisk() *Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

var File_disk_manager_proto protoreflect.FileDescriptor

const file_disk_manager_proto_rawDesc = "" +
	"\n" +
	"\x12disk_manager.proto\"\x06\n" +
	"\x04Void\"\x97\x01\n" +
	"\x04Disk\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12\x1b\n" +
	"\tdisk_name\x18\x02 \x01(\tR\bdiskName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\x06format\x18\x04 \x01(\x0e2\v.DiskFormatR\x06format\x12\x12\n" +
	"\x04size\x18\x05 \x01(\rR\x04size\".\n" +
	"\x11CreateDiskRequest\x12\x19\n" +
	"\x04disk\x18\x01 \x01(\v2\x05.DiskR\x04disk\">\n" +
	"\x12CreateDiskResponse\x12(\n" +
	"\fcreated_disk\x18\x01 \x01(\v2\x05.DiskR\vcreatedDisk\",\n" +
	"\x11DeleteDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\".\n" +
	"\x11UpdateDiskRequest\x12\x19\n" +
	"\x04disk\x18\x01 \x01(\v2\x05.DiskR\x04disk\"\x11\n" +
	"\x0fListDiskRequest\"-\n" +
	"\x10ListDiskResponse\x12\x19\n" +
	"\x04disk\x18\x01 \x03(\v2\x05.DiskR\x04disk\"F\n" +
	"\x0eGetDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12\x1b\n" +
	"\tdisk_name\x18\x02 \x01(\tR\bdiskName\",\n" +
	"\x0fGetDiskResponse\x12\x19\n" +
	"\x04disk\x18\x01 \x01(\v2\x05.DiskR\x04disk* \n" +
	"\n" +
	"DiskFormat\x12\a\n" +
	"\x03raw\x10\x00\x12\t\n" +
	"\x05qcow2\x10\x012\xff\x01\n" +
	"\vDiskManager\x127\n" +
	"\n" +
	"CreateDisk\x12\x12.CreateDiskRequest\x1a\x13.CreateDiskResponse\"\x00\x12)\n" +
	"\n" +
	"DeleteDisk\x12\x12.DeleteDiskRequest\x1a\x05.Void\"\x00\x12)\n" +
	"\n" +
	"UpdateDisk\x12\x12.UpdateDiskRequest\x1a\x05.Void\"\x00\x121\n" +
	"\bListDisk\x12\x10.ListDiskRequest\x1a\x11.ListDiskResponse\"\x00\x12.\n" +
	"\aGetDisk\x12\x0f.GetDiskRequest\x1a\x10.GetDiskResponse\"\x00B'Z%github.com/fanyang89/easyvirt/v1/diskb\x06proto3"

var (
	file_disk_manager_proto_rawDescOnce sync.Once
	file_disk_manager_proto_rawDescData []byte
)

func file_disk_manager_proto_rawDescGZIP() []byte {
	file_disk_manager_proto_rawDescOnce.Do(func() {
		file_disk_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disk_manager_proto_rawDesc), len(file_disk_manager_proto_rawDesc)))
	})
	return file_disk_manager_proto_rawDescData
}

var file_disk_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_disk_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_disk_manager_proto_goTypes = []any{
	(DiskFormat)(0),            // 0: DiskFormat
	(*Void)(nil),               // 1: Void
	(*Disk)(nil),               // 2: Disk
	(*CreateDiskRequest)(nil),  // 3: CreateDiskRequest
	(*CreateDiskResponse)(nil), // 4: CreateDiskResponse
	(*DeleteDiskRequest)(nil),  // 5: DeleteDiskRequest
	(*UpdateDiskRequest)(nil),  // 6: UpdateDiskRequest
	(*ListDiskRequest)(nil),    // 7: ListDiskRequest
	(*ListDiskResponse)(nil),   // 8: ListDiskResponse
	(*GetDiskRequest)(nil),     // 9: GetDiskRequest
	(*GetDiskResponse)(nil),    // 10: GetDiskResponse
}
var file_disk_manager_proto_depIdxs = []int32{
	0,  // 0: Disk.format:type_name -> DiskFormat
	2,  // 1: CreateDiskRequest.disk:type_name -> Disk
	2,  // 2: CreateDiskResponse.created_disk:type_name -> Disk
	2,  // 3: UpdateDiskRequest.disk:type_name -> Disk
	2,  // 4: ListDiskResponse.disk:type_name -> Disk
	2,  // 5: GetDiskResponse.disk:type_name -> Disk
	3,  // 6: DiskManager.CreateDisk:input_type -> CreateDiskRequest
	5,  // 7: DiskManager.DeleteDisk:input_type -> DeleteDiskRequest
	6,  // 8: DiskManager.UpdateDisk:input_type -> UpdateDiskRequest
	7,  // 9: DiskManager.ListDisk:input_type -> ListDiskRequest
	9,  // 10: DiskManager.GetDisk:input_type -> GetDiskRequest
	4,  // 11: DiskManager.CreateDisk:output_type -> CreateDiskResponse
	1,  // 12: DiskManager.DeleteDisk:output_type -> Void
	1,  // 13: DiskManager.UpdateDisk:output_type -> Void
	8,  // 14: DiskManager.ListDisk:output_type -> ListDiskResponse
	10, // 15: DiskManager.GetDisk:output_type -> GetDiskResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_disk_manager_proto_init() }
func file_disk_manager_proto_init() {
	if File_disk_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disk_manager_proto_rawDesc), len(file_disk_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_disk_manager_proto_goTypes,
		DependencyIndexes: file_disk_manager_proto_depIdxs,
		EnumInfos:         file_disk_manager_proto_enumTypes,
		MessageInfos:      file_disk_manager_proto_msgTypes,
	}.Build()
	File_disk_manager_proto = out.File
	file_disk_manager_proto_goTypes = nil
	file_disk_manager_proto_depIdxs = nil
}
