// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Disk is the predicate function for disk builders.
type Disk func(*sql.Selector)

// VM is the predicate function for vm builders.
type VM func(*sql.Selector)
